apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices
spec:
  selector:
    matchLabels:
      app: microservices
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 10s
