# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  alertmanager:
    service:
      type: NodePort
  server:
    service:
      type: NodePort

grafana:
  server:
    service:
      type: NodePort
