# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This umbrella chart is derived from instructions found here:
# https://github.com/coreos/prometheus-operator/tree/master/helm

prometheus-operator:
  rbacEnable: false

  alertmanager:
    service:
      type: NodePort
  server:
    service:
      type: NodePort

kube-prometheus:
  server:
    service:
      type: NodePort
